export default {
    GET_FEW_ADVERTS_SUCCESSFUL: 'GET_FEW_ADVERTS_SUCCESSFUL',
    GET_USER_ADVERTS_SUCCESSFUL: 'GET_USER_ADVERTS_SUCCESSFUL',
    ADD_ADVERT_SUCCESSFUL: 'ADD_ADVERT_SUCCESSFUL',
    REMOVE_ADVERT_SUCCESSFUL: 'REMOVE_ADVERT_SUCCESSFUL'
};