export default {
    GET_FEW_ADVERTS_SUCCESSFUL: 'GET_FEW_ADVERTS_SUCCESSFUL',
    GET_AUTHORS_ADVERTS_SUCCESSFUL: 'GET_AUTHORS_ADVERTS_SUCCESSFUL',
    GET_INTERESTED_ADVERTS_SUCCESSFUL: 'GET_INTRESTED_ADVERTS_SUCCESSFUL',
    ADD_ADVERT_SUCCESSFUL: 'ADD_ADVERT_SUCCESSFUL',
    REMOVE_ADVERT_SUCCESSFUL: 'REMOVE_ADVERT_SUCCESSFUL',
    CHANGE_ADVERT_SUCCESSFUL: 'CHANGE_ADVERT_SUCCESSFUL'
};