export default { 
    USER_AUTH_SUCCESSFUL: 'USER_AUTH_SUCCESSFUL',
    USER_AUTH_FAILURE: 'USER_AUTH_FAILURE',
    LOG_IN_SUCCESSFUL: 'LOG_IN_SUCCESSFUL',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',
    SIGN_UP_SUCCESSFUL: 'SIGN_UP_SUCCESSFUL',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    LOG_OUT: 'LOG_OUT',
    
};
