export default {
    GET_USER_SUCCESSFUL: 'GET_USER_SUCCESSFUL',
    GET_USER_FAILURE: 'GET_USER_FAILURE',
    LOG_IN_SUCCESSFUL: 'LOG_IN_SUCCESSFUL',
    LOG_IN_FAILURE: 'LOG_IN_FAILURE',
    SIGN_UP_SUCCESSFUL: 'SIGN_UP_SUCCESSFUL',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    LOG_OUT: 'LOG_OUT',
    СHANGE_AVATAR_SUCCESSFUL: 'СHANGE_AVATAR_SUCCESSFUL',
    СHANGE_AVATAR_FAILURE: 'СHANGE_AVATAR_FAILURE'
};
